### PR TITLE
Development

### PR DESCRIPTION
**Pull request by gferrarocamus**
Project: "Building with Responsive Design"

### CODE REVIEW

**Comment by dipto0321** [comment]
Hi guys @gferrarocamus and @1ba1 ,
Good job 👏 . Couple of things you need to do before merging into the master branch. Your code is clean there is no doubt. Media queries also good. But there is a huge difference with the original site and your one. So please try to make this at least 65% to 70% like the main site (please check out below picture). Besides that, I want to request you please organize all your files. Let me pointed out those things bellow one by one : 
1. It will look nice if you create a folder `assets` and put all folders like `CSS`, `images`, `js` etc. In your case, you need to move images inside a new folder and put that inside the `assets` folder and also create a `css` folder and put all your `.css` files inside there no matter if there is only one `.css` file. Why you need this, it will help you to organize your project's files.
2. Please separate resetting codes from `styles.css` in a new `.css` file.
3.  This image. I have pointed those from original site so that you can understand (This is full hd view)
 Pointed portion does not look good in your site.
4. After implement those changes please check your site with chrome developer mobile view. And compare it to the original site. Because there are most of the parts will change when it will meet different device size.

#### Again, You don't need to make it 100% perfect. But try your best to make it 65%-70%

**Note:** Please don't forget to check your template with w3Validator after implementing those changes.  Send another code review request after those changes.  Let me know if you have any question. Just knock me on slack. Best of luck.

Thanks 🙏

**Comment by gferrarocamus** [comment]
@dipto0321 - Thank you so much for your review!

One question about the header. We were aiming at this version of the site (which was live yesterday): https://web.archive.org/web/20190305092250/https://thenextweb.com/

That is why you can see three "featured articles" on the header, instead of just one:
screenshot from 2019-03-06 16-40-55

Should we change this header to match today's version of thenextweb.com, or can we continue with the header as it is in the image above?

Thank you!

**Comment by dipto0321** [comment]
Thanks @gferrarocamus  for pointing this 🙂 ,
At that situation, you don't need to do anything with this. Just try to implement other's I mentioned on those reviews. 😄 ☺️  Please add a  demo link on your readme.

**Comment by dipto0321** [comment]
# Well done Guys 🏆 🍔 
Hi, @gferrarocamus and @1ba1,
You successfully completed all those changes that I mentioned to you. Congratulation for this. Before merging this project. Just update your readme with the contributor names with their corresponding Github profile link, A good title (You can use `The Next Web homepage replica ` as the title) and a little bit description about this project like what you learn from this project, what kind of technologies you used for this project etc. Don't forget to use markdown for styling your readme after adding ☝️ that information. [Here ](https://www.markdownguide.org/basic-syntax) is a guideline for [markdown](https://www.markdownguide.org/getting-started).

After that, I think you can merge into master. 👍 

_Note: Don't need to send a further request for code re-review. Happy Coding!_

**Comment by gferrarocamus** [comment]
Thanks, @dipto0321!

**Pull request merged**
